# Generated by Django 6.0.1 on 2026-02-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter', '0002_alter_portfolio_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
